### ISSUE TITLE
Not Collapsing with Qlik Sense 2.1.1 

### ISSUE THREAD

**Issue by MDamon** [yianni-ververis/SenseUI-DropDown#1]
Would be a great extension as Qlik Sense has horrible drop down implementation right now.. Unfortunately it doesn't collapse and just shows a dump of your Dimension.

**Comment by yianni-ververis** [comment]
I have 2.1.1 and it works fine.

Are you running it locally? Desktop? server? 

It seems that it does not access the css file.

**Comment by yianni-ververis** [comment]
![screenshot2](https://cloud.githubusercontent.com/assets/12610095/12126681/a85bb374-b3c0-11e5-95eb-8b28960a6983.png)
