### ISSUE TITLE
Glitch with Desktop version 3.1.3

### ISSUE THREAD

**Issue by ghost** [yianni-ververis/SenseUI-DropDown#5]
it looks like in senseui-dropdown.js it cannot find "core.utils/theme", when using Desktop version 3.1.3, so I commented out this line, removed Theme, from line 10 and amended line 249 & 250 to :

    // Button Colors
    vars.btnBgColor = layout.btnBgColorHex ;
    vars.btnTxtColor = layout.btnTxtColorHex ;
And it seems to work ok, apart from the overlay issue.

**Comment by yianni-ververis** [comment]
Yeah the Theme isnot there on SR2. This is fixed on SR3 though.

Thank you
yianni

**Comment by ghost** [comment]
Strange.  On my QlikSense Desktop 3.1 SR3, 10.7.2 the folder is not there.

**Comment by sdbarron** [comment]
@BillMarkham Would you mind forking and sharing your changed version?

**Comment by yianni-ververis** [comment]
@sdbarron I just removed the themes. is not used and the folder that is poitning to ahs been changed in SR2. you need to update to SR3. SR2 will affect all of your extensions if the use the Theme file

**Comment by sdbarron** [comment]
So, in SR3, I should be able to use as-is?  Or do I need to remove the word Theme from line 10?  Any idea of version requirements for Enterprise?

**Comment by yianni-ververis** [comment]
Yes. I have updated my git repo so you can download and use this one or you can remove it yourself or you can upgrade to SR3.

**Comment by yianni-ververis** [comment]
Hold on it seems I did not commit! In one second...

**Comment by sdbarron** [comment]
lol, OK - I had looked but didn't see it.  Thanks for the update!

**Comment by yianni-ververis** [comment]
My apologies to everyone. The removal of the Theme was for another exstension! Hte extension is using it to default the color palette. So I would suggest to upgrade to SR3

**Comment by yianni-ververis** [comment]
If you want to remove it you need to default to a specific color in Line 249 and 250 like 
vars.btnBgColor = (layout.btnBgColorHex !== '') ? layout.btnBgColorHex : #CCCCCC;
vars.btnTxtColor = (layout.btnTxtColorHex !== '') ? layout.btnTxtColorHex : #FFFFFF;

**Comment by yianni-ververis** [comment]
OK, I pushed the new fix for >=3.1.2. You can download the extension again.

I replaced the "core.utils/theme" with 
"text!themes/old/sense/theme.json"
